FROM fedora:35

RUN dnf update -y \
    && \
    dnf groupinstall -y \
        "Development Tools" \
        "Development Libraries" \
    && dnf clean all \
  	&& rm -rf /var/cache/dnf

RUN dnf update -y \
    && \
    dnf install -y \
        gcc \
        rpm-build \
        rpm-devel \
        rpmlint \
        make \
        python \
        bash \
        coreutils \
        diffutils \
        patch \
        rpmdevtools \
        desktop-file-utils \
    && dnf clean all \
  	&& rm -rf /var/cache/dnf

RUN dnf update -y \
    && \
    dnf install -y \
        ncurses-devel \
        SDL2-devel \
        SDL2_image-devel \
        SDL2_ttf-devel \
        SDL2_mixer-devel \
        python3-docutils \
    && dnf clean all \
  	&& rm -rf /var/cache/dnf
    
ADD build.sh /opt/rpm/build.sh
ADD angband.spec /opt/rpm/angband.spec
ADD angband.png /opt/rpm/angband.png
ADD angband.desktop /opt/rpm/angband.desktop
ADD generate-tarball.sh /opt/rpm/generate-tarball.sh

WORKDIR /opt/rpm/
CMD ./build.sh


